# Generated by Django 6.0.7 on 2026-08-01 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0002_users_profile_role"),
        ("graduates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graduate",
            name="faculty_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.faculty",
            ),
        ),
    ]
