# Generated by Django 6.0.7 on 2026-08-01 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graduates", "0002_alter_graduate_faculty_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty_turn",
            name="faculty_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.faculty",
            ),
        ),
        migrations.AlterField(
            model_name="graduate",
            name="faculty_turn_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="graduates.faculty_turn",
            ),
        ),
        migrations.AlterField(
            model_name="graduate",
            name="nationality_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.nationality",
            ),
        ),
        migrations.AlterField(
            model_name="graduate",
            name="regulation_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.regulation",
            ),
        ),
        migrations.AlterField(
            model_name="graduate",
            name="specialization_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.specialization",
            ),
        ),
        migrations.AlterField(
            model_name="graduate",
            name="transaction_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.transaction",
            ),
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "history_id",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(blank=True, null=True)),
                (
                    "history_field",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "history_old",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "history_new",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "history_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "history_desc",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "authunticated_user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administration.authenticated_user",
                    ),
                ),
                (
                    "faculty_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administration.faculty",
                    ),
                ),
                (
                    "row_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graduates.graduate",
                    ),
                ),
            ],
            options={
                "ordering": ("history_id",),
            },
        ),
    ]
