# Generated by Django 6.0.7 on 2026-08-02 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0006_alter_section_section_ar_namr_and_more"),
        ("graduates", "0005_rename_faculty_id_faculty_turn_faculty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="graduate",
            field=models.ForeignKey(
                blank=True,
                db_column="graduate",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="graduates.graduate",
            ),
        ),
        migrations.AlterField(
            model_name="graduate",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                db_column="faculty",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graduates",
                to="administration.faculty",
            ),
        ),
        migrations.AlterField(
            model_name="graduate",
            name="faculty_turn",
            field=models.ForeignKey(
                blank=True,
                db_column="faculty_turn",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="graduates.faculty_turn",
            ),
        ),
        migrations.AlterField(
            model_name="graduate",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                db_column="nationality",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.nationality",
            ),
        ),
        migrations.AlterField(
            model_name="graduate",
            name="regulation",
            field=models.ForeignKey(
                blank=True,
                db_column="regulation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.regulation",
            ),
        ),
        migrations.AlterField(
            model_name="graduate",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                db_column="specialization",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.specialization",
            ),
        ),
        migrations.AlterField(
            model_name="graduate",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                db_column="transaction",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="authunticated_user_id",
            field=models.ForeignKey(
                blank=True,
                db_column="authunticated_user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.authenticated_user",
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                db_column="faculty",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.faculty",
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="graduate",
            field=models.ForeignKey(
                db_column="graduate",
                on_delete=django.db.models.deletion.CASCADE,
                to="graduates.graduate",
            ),
        ),
    ]
