# Generated by Django 6.0.7 on 2026-08-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authenticated_user',
            fields=[
                ('authunticated_user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('authorize_user_id', models.BigIntegerField()),
                ('faculty_id', models.BigIntegerField()),
                ('isadd', models.CharField(max_length=2)),
                ('isedit', models.CharField(max_length=2)),
                ('isdelete', models.CharField(max_length=2)),
                ('isprint', models.CharField(max_length=2)),
                ('iscommit', models.CharField(max_length=2)),
                ('isview', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ('authunticated_user_id',),
            },
        ),
        migrations.CreateModel(
            name='authorize_user',
            fields=[
                ('authorize_user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('motherboard_id', models.BigIntegerField()),
                ('isfirstlog', models.CharField(max_length=20)),
                ('browser', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ('authorize_user_id',),
            },
        ),
        migrations.CreateModel(
            name='certificate_counter',
            fields=[
                ('certificate_counter_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('graduate_id', models.BigIntegerField()),
                ('certificate_count', models.BigIntegerField()),
                ('certificate_date', models.DateTimeField()),
                ('certificate_user', models.BigIntegerField()),
                ('certificate_type', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('certificate_counter_id',),
            },
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('data_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('super_name', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('admin_en', models.CharField(max_length=100)),
                ('super_en', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('data_id',),
            },
        ),
        migrations.CreateModel(
            name='degree',
            fields=[
                ('degree_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('degree_ar_name', models.CharField(max_length=200)),
                ('degree_en_name', models.CharField(max_length=200)),
                ('faculty_id', models.BigIntegerField()),
            ],
            options={
                'ordering': ('degree_id',),
            },
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('faculty_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('faculty_ar_name', models.CharField(max_length=200)),
                ('faculty_en_name', models.CharField(max_length=200)),
                ('faculty_email', models.CharField(blank=True, max_length=100, null=True)),
                ('faculty_ar_dean', models.CharField(max_length=200)),
                ('faculty_en_dean', models.CharField(max_length=200)),
                ('faculty_gawda_no', models.IntegerField(blank=True, null=True)),
                ('faculty_gawda_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('faculty_id',),
            },
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('grade_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('grade_ar_name', models.CharField(max_length=40)),
                ('grade_en_name', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('grade_id',),
            },
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('history_id', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('table_id', models.BigIntegerField()),
                ('row_id', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('history_date', models.DateTimeField(blank=True, null=True)),
                ('history_field', models.CharField(blank=True, max_length=400, null=True)),
                ('history_old', models.CharField(blank=True, max_length=400, null=True)),
                ('history_new', models.CharField(blank=True, max_length=400, null=True)),
                ('history_type', models.CharField(blank=True, max_length=20, null=True)),
                ('history_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('authunticated_user_id', models.BigIntegerField(blank=True, null=True)),
                ('faculty_id', models.BigIntegerField()),
            ],
            options={
                'ordering': ('history_id',),
            },
        ),
        migrations.CreateModel(
            name='motherboard',
            fields=[
                ('motherboard_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('motherboard_serial', models.CharField(max_length=100)),
                ('motherboard_computer', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('motherboard_id',),
            },
        ),
        migrations.CreateModel(
            name='nationality',
            fields=[
                ('nationality_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nationality_ar_name', models.CharField(max_length=200)),
                ('nationality_en_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nationality_id',),
            },
        ),
        migrations.CreateModel(
            name='regulation',
            fields=[
                ('regulation_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('regulation_ar_name', models.CharField(max_length=200)),
                ('degree_id', models.BigIntegerField()),
            ],
            options={
                'ordering': ('regulation_id',),
            },
        ),
        migrations.CreateModel(
            name='regulation_grade',
            fields=[
                ('regulation_grade_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('regulation_id', models.BigIntegerField()),
                ('grade_id', models.BigIntegerField()),
                ('grade_start', models.SmallIntegerField()),
                ('grade_end', models.SmallIntegerField()),
            ],
            options={
                'ordering': ('regulation_grade_id',),
            },
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('section_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('section_ar_namr', models.CharField(max_length=400)),
                ('section_en_name', models.CharField(blank=True, max_length=400, null=True)),
                ('faculty_id', models.BigIntegerField()),
            ],
            options={
                'ordering': ('section_id',),
            },
        ),
        migrations.CreateModel(
            name='specialization',
            fields=[
                ('specialization_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('specialization_ar_name', models.CharField(max_length=400)),
                ('specialization_en_name', models.CharField(max_length=400)),
                ('section_id', models.BigIntegerField()),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('ishours', models.CharField(blank=True, max_length=2, null=True)),
                ('gawda_no', models.IntegerField(blank=True, null=True)),
                ('gawda_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('specialization_id',),
            },
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('transaction_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('user_id', models.BigIntegerField()),
                ('transaction_descripsion', models.CharField(max_length=100)),
                ('faculty_id', models.BigIntegerField()),
            ],
            options={
                'ordering': ('transaction_id',),
            },
        ),
        migrations.CreateModel(
            name='upload_error',
            fields=[
                ('error_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('faculty_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('graduate_id_card', models.CharField(blank=True, max_length=20, null=True)),
                ('error_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('error_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('error_id',),
            },
        ),
        migrations.CreateModel(
            name='users_profile',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=60)),
                ('user_short_name', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=130)),
                ('user_email', models.CharField(max_length=40)),
                ('user_status', models.CharField(max_length=4)),
                ('user_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('isadmin', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
    ]
