# Generated by Django 6.0.7 on 2026-08-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_rename_faculty_id_section_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_ar_namr',
            field=models.CharField(db_column='section_ar_namr', max_length=400),
        ),
        migrations.RenameField(
            model_name='section',
            old_name='section_ar_namr',
            new_name='section_ar_name',
        ),
    ]
