# Generated by Django 6.0.7 on 2026-08-02 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0006_alter_section_section_ar_namr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regulation",
            name="degree_id",
        ),
        migrations.AddField(
            model_name="regulation",
            name="degree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.degree",
            ),
        ),
    ]
