# Generated by Django 6.0.7 on 2026-08-02 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0008_alter_regulation_degree"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regulation_grade",
            name="grade_id",
        ),
        migrations.RemoveField(
            model_name="regulation_grade",
            name="regulation_id",
        ),
        migrations.AddField(
            model_name="regulation_grade",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.grade",
            ),
        ),
        migrations.AddField(
            model_name="regulation_grade",
            name="regulation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.regulation",
            ),
        ),
    ]
