SELECT
	GRADUATES_GRADUATE.GRADUATE_ID,
	LPAD(GRADUATES_GRADUATE.FACULTY::TEXT, 2, '0') || GRADUATES_FACULTY_TURN.TURN_YEAR || RIGHT(GRADUATES_GRADUATE.GRADUATE_ID_CARD::TEXT, 4) || LPAD(
		SUBSTR(
			(GRADUATES_GRADUATE.GRADUATE_ID * SCORE)::TEXT,
			1,
			4
		),
		4,
		'0'
	) AS "IK"
FROM
	GRADUATES_GRADUATE,
	GRADUATES_FACULTY_TURN
WHERE
	GRADUATES_GRADUATE.FACULTY_TURN = GRADUATES_FACULTY_TURN.FACULTY_TURN_ID
ORDER BY
	GRADUATE_ID;